version: '3.9'


services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  pinger:
    image: pinger:latest
    ports:
      - 3300:3300
    environment:
      LISTEN_PORT: 3300
      RABBITMQ_SERVER_URL: amqp://rabbitmq:5672
  ponger: 
    image: ponger:latest
    environment:
      LISTEN_PORT: 4200
      RABBITMQ_SERVER_URL: amqp://rabbitmq:5672