FROM golang:1.18 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o pinger ./cmd/pinger/main.go

# final (target) stage

FROM scratch
COPY --from=builder /app/pinger /
CMD ["/pinger"]